Task3
joannamariawolska/invoicing-system-joanna-wolska pull request #4
Opened 2023-03-01 17:02 UTC by joannamariawolska

2023-03-04 09:29 UTC, patryk-stepniak approved these changes

2023-03-04 09:29 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/App.java
> +    Company seller = new Company("555-156-82-10", "85-805 Bydgoszcz, Gdańska 13", "Development");
Bydgoszcz <3

2023-03-04 09:29 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/db/file/FileBasedDatabase.java
> +    return line.contains("\"id\":" + id + ",");
To rozwiązanie może okazać się problematyczne w przyszłości, ale na ten moment niech będzie.

2023-03-04 09:31 UTC, patryk-stepniak requested changes
Zadanie numer 3 wykonane super, jednak przy buildzie nie jest sprawdzane pokrycie testami. Jest to coś co powinno zostać zaimplementowane w zadaniu numer 2. Popraw to proszę.

2023-03-07 16:47 UTC, marwis1995 approved these changes

2023-03-07 16:47 UTC, merged